"""add research workflow checkpoint

Revision ID: 56634d6b7215
Revises: 6a2d698ce84e
Create Date: 2026-09-09 11:17:31.540560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56634d6b7215'
down_revision: Union[str, Sequence[str], None] = '6a2d698ce84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('workflow_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'workflow_state')
    # ### end Alembic commands ###
